# Generated by Django 3.0.8 on 2020-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200724_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgame',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='start_time',
            field=models.IntegerField(default=1595596690.237582),
        ),
    ]
