# Generated by Django 3.0.8 on 2020-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200724_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='start_time',
            field=models.IntegerField(default=1595596900.886134),
        ),
    ]
