# Generated by Django 3.0.8 on 2020-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200724_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
