# Generated by Django 3.0.8 on 2020-07-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200724_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
