# Generated by Django 3.0.8 on 2020-07-24 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200724_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 21, 8, 11, 923172)),
        ),
    ]
