# Generated by Django 3.0.8 on 2020-07-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200724_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedquestion',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Course'),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Course'),
        ),
    ]
